### PR TITLE
Fix type definition

### LINKED ISSUE #29: The type definition in v3 is broken
The default export was removed in this commit: https://github.com/sindresorhus/p-limit/commit/b35faf54fb0871d9ae592069a18083a2ba15d8a9#diff-168726dbe96b3ce427e7fedce31bb0bcL65

However, the `.d.ts` file still suggests there is a default export

### PR DESCRIPTION
**Pull request by zkochan**
close #29

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for catching that

**Comment by zkochan** [comment]
sorry, it appears I also had to fix the type definition tests. Should I push new PR with that fix?

**Comment by zkochan** [comment]
ok, I see you fixed that. Thanks

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-limit/releases/tag/v3.0.1

**Pull request merged**
